### PR TITLE
Add mailchimp SPF/DKIM records to improve deliverability

### PR DESCRIPTION
**Pull request by RealOrangeOne**
https://mailchimp.com/help/set-up-custom-domain-authentication-dkim-and-spf/#verify+domain+and+copy+records

image

### CODE REVIEW

**Review by jimmythompson — APPROVED** [review]

**Review by trickeydan — APPROVED** [review]
I'm kinda surprised that we didn't have these in before. Most email servers will outright reject anything without a SPF record, and junk anything without a valid DKIM.

**Comment by trickeydan** [comment]
Please could this be merged? We (KTC) would like to ensure that our invitation to join the KT emailed is delivered.

**Comment by RealOrangeOne** [comment]
> Please could this be merged?

There's an implied presidence on the contents of `master` being what's deployed, which I think we should keep.

In theory i've got access to do this, although I've not had a chance (or the courage) to tinker, although I'm sure i'll find some time at some point to get on top of this repo.

**Comment by trickeydan** [comment]
> > Please could this be merged?
> 
> There's an implied presidence on the contents of `master` being what's deployed, which I think we should keep.
> 
> In theory i've got access to do this, although I've not had a chance (or the courage) to tinker, although I'm sure i'll find some time at some point to get on top of this repo.

*Please could this be deployed?

**Comment by trickeydan** [comment]
> Please could this be deployed?

Ping on this. We'd really like the Kit Team emails to *not go to spam* ideally.

**Comment by RealOrangeOne** [comment]
No emails should go to spam, kit team or otherwise.

I've started the cleanup and rebuild work (#11), but haven't had the time to finish it quite yet.

**Comment by RealOrangeOne** [comment]
In the interest of email deliverability, i've applied this PR manually.

The current state is wildly out of date, so i'm not too annoyed it's further diverged. I'll address that once I get a chance to look at #11 again.

image

**Pull request merged**
